# Minimal Hyprland entry point
# Sources the shared Hyprland config and starts common desktop helpers.

source = /home/prieyan/.config/hypr/hypr.conf

# Common autostart helpers
exec-once = eww daemon
exec-once = eww open bar
exec-once = hyprpaper
exec-once = /home/prieyan/.config/hypr/scripts/wallpaper.sh init
# Start the hypridle daemon for locking and sleep management
exec-once = hypridle
# Notification daemon (top-right)
exec-once = mako --config /home/prieyan/.config/hypr/apps/mako/config
exec-once = nm-applet --indicator
exec-once = blueman-applet
